[world creator] add prototype
serykhelena/AutoNetChallenge pull request #23
Opened 2019-10-23 13:05 UTC by PonomarevDA

2019-10-30 15:55 UTC, KaiL4eK requested changes
- Нет поддержки опций командной строки, думаю, стоит добавить, так как через них можно задать размер сетки, в которой будем работать. Помимо этого через опции можно передать начальный файл, из которого подгрузить карту, чтобы не делать доп поля в интерфейсе, так как и так хватает пока)
- Если вообще ничего не добавлять на карту и нажать Generate JSON - приложение падает
- Может упускаю, но не видно, чему равен размер одной ячейки. Это должно быть задано от пользователя и учтено в работе всего интерфейса. Юзер сам говорит, чему равна одна ячейка - 2м или 10 см. При этом в интерфейсе это никак не скажется, так как эти размеры нужны при генерации SDF.
В остальном хорошая организация, побольше и поувереннее бы использовать ООП.

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/README.md
> +After that you should consistently click on buttons `create json` and `create sdf from json`.
Может быть сделать кнопку `create sdf from json` такой, чтобы она сразу генерила карту без необходимости создавать JSON + сделать маленький скрипт .py, который генерить sdf из JSON. Тогда не требуется хранить sdf в репозитории, так как всегда можно сгенерить этим скриптом или подгрузить в world_creator.py и нажать генерацию.

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/install.sh
> +sudo apt install python3-qt5 pyqt5-dev-tools qtcreator python3-lxml python3-numpy
Не уверен, что qtcreator нужен для работы.

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/install.sh
> +sudo apt install python3-qt5 pyqt5-dev-tools qtcreator python3-lxml python3-numpy
Если требуется установить только python пакеты - обычно пишется requirements.txt, в котором просто перечисляются пакеты, необходимые для работы

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/gazebo_sdf.py
> +        boxSize = Point(CELL_SIZE[0], CELL_SIZE[1], WALL_HEGHT)
Так как это обозначение размера, думаю, стоит ввести класс Size, если требуется - даже Size3D. Даже если у нас тот же самый функционал, но название класса говорит о многом, как и поля класса.

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/gazebo_sdf.py
> +        @brief Spawn big box with size 2x2 on middle of cell
Почему box фиксирован размером 2х2? Нельзя создать box 1х1? Это будет более универсальный вариант.

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/gazebo_sdf.py
> +    def addBox(self, cellIndexes):
Почему бы не ввести термин Point2D, чтобы передавать не массивом, а объектом?

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/gazebo_sdf.py
> +            posOffset = [0.15, 0.15]
Думаю, стоит офсеты добавить константами, их слишком много и при исправлении придется долго фиксить

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/json_converter.py
> +SDF_DEFAULT_NAME = "../wr8_description/worlds/world.world"
Не стоит так делать, лучше оставить это на откуп пользователя, так как интуитивно не понятно, что файл кинется туда, пока не прочитаешь код

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/json_converter.py
> +    return list([ int(mapPose[0] / 2), int(mapPose[1] / 2) ])
Зачем такая сильная привязка к 2? То, что было написано в регламенте соревнований легко покрывается, если пользователь сам будет создавать в два раза больше объектов и задавать размеры в 2 раза больше, при этом если мы заложимся на атомарный размер = 2, то единичные объекты для нас не будут доступны.

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/json_converter.py
> +            walls.append([p1, p2])
Для такого случая рекомендую создать класс Wall, чтобы не кидаться массивами. Более того, можно создать класс GazeboObject и InterfaceObject, в которых будет функционал перевода из координат одного в координаты другого, при этом все остальные объекты будут наследоваться от него.

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/gui.py
> +        self.initMap(18, 18)
Вот в этом место можно передать инфу от пользователя о количестве ячеек

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/gui.py
> +        self.CELLS_SIZE_IN_METERS = [2, 2]
И все таки, эту штуку лучше получить от пользователя

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/gui.py
> +        self.CELLS_AMOUNT = [ int(self.MAP_SIZE[0]/self.CELLS_SIZE_IN_METERS[0]),
Думаю, лучше, чтобы количество ячеек определял напрямую пользователь, а мы уже при генерации физического мира использовали реальный размер

2019-10-30 15:55 UTC, KaiL4eK commented on world_creator/gui.py
> +    def paintEvent(self, event=None):
Добавление каждого нового типа объектов ведет к написанию новой строки =)
Я бы сделал базовый класс, который обязательно имеет метод render, после наследовался от него и просто держал список объектов, а здесь дергал наследованные методы из этого списка.

2019-10-30 17:39 UTC, PonomarevDA commented on world_creator/README.md
> +After that you should consistently click on buttons `create json` and `create sdf from json`.
Кажется, я немного не понял идею.
`Тогда не требуется хранить sdf в репозитории, так как всегда можно сгенерить этим скриптом или подгрузить в world_creator.py и нажать генерацию`.
Но при текущих кнопках и так не обязательно хранить sdf, его можно сделать в world creator из json, нажав "load json" и "create sdf from json".

2019-10-30 17:42 UTC, PonomarevDA commented on world_creator/install.sh
> +sudo apt install python3-qt5 pyqt5-dev-tools qtcreator python3-lxml python3-numpy
Согласен с замечанием. Исправлю.

2019-10-30 17:42 UTC, PonomarevDA commented on world_creator/install.sh
> +sudo apt install python3-qt5 pyqt5-dev-tools qtcreator python3-lxml python3-numpy
Согласен с замечанием. Исправлю.

2019-10-30 17:43 UTC, PonomarevDA commented on world_creator/gazebo_sdf.py
> +        boxSize = Point(CELL_SIZE[0], CELL_SIZE[1], WALL_HEGHT)
Согласен. Добавлю.

2019-10-30 17:45 UTC, PonomarevDA commented on world_creator/gazebo_sdf.py
> +        @brief Spawn big box with size 2x2 on middle of cell
По логике этого метода, размер box определяется размерами ячейки. Может быть, метод даже стоит переименовать на addCellBox или в этом духе.
Тем не менее, 2х2 - это явно ошибка в комментарии. Исправлю.

2019-10-30 17:47 UTC, PonomarevDA commented on world_creator/gazebo_sdf.py
> +    def addBox(self, cellIndexes):
Согласен. Добавлю такой класс.

2019-10-30 17:49 UTC, PonomarevDA commented on world_creator/gazebo_sdf.py
> +            posOffset = [0.15, 0.15]
Согласен. В этом методе ещё и краткий комментарий скопирован и не поменялся. Исправлю.

2019-10-30 17:54 UTC, PonomarevDA commented on world_creator/json_converter.py
> +SDF_DEFAULT_NAME = "../wr8_description/worlds/world.world"
Согласен. Удалю этот хардкод и добавлю диалоги в соответствующие кнопки, чтобы юзер сам выбрал.

2019-10-30 17:55 UTC, PonomarevDA commented on world_creator/json_converter.py
> +    return list([ int(mapPose[0] / 2), int(mapPose[1] / 2) ])
Признаю косяк. Исправлю.

2019-10-30 18:06 UTC, PonomarevDA commented on world_creator/gui.py
> +        self.initMap(18, 18)
Планировалось, что юзер с помощью кнопок на панели управления будет задавать размер карты и размер ячеек.
18x18 и 2x2 - это дефолтные значения размеров карты и ячеек.
Добавлю в аргументы метода и размер ячеек.

2019-10-30 18:07 UTC, PonomarevDA commented on world_creator/gui.py
> +        self.CELLS_SIZE_IN_METERS = [2, 2]
Исправлю.

2019-10-30 18:09 UTC, PonomarevDA commented on world_creator/gui.py
> +        self.CELLS_AMOUNT = [ int(self.MAP_SIZE[0]/self.CELLS_SIZE_IN_METERS[0]),
Исправлю.

2019-10-30 18:45 UTC, PonomarevDA commented on world_creator/gui.py
> +    def paintEvent(self, event=None):
Согласен. Еще добавлю следующее:
- аналогично с методом mousePressEvent
- у каждого объекта есть callback обработки нажатия на кнопку.

Таким образом, 3 общих метода + конструктор кнопки.
На днях составил что-то похожее на [UML диаграмму]( https://drive.google.com/file/d/1O1Lk57hbekq3XuofFHd3WIHYmH5pl4MT/view?usp=sharing).
И реализовал все это на локальной ветке refactoring.
Причешу код, исправлю твои замечания и залью все это в эту ветку.

2019-10-30 18:49 UTC, PonomarevDA commented on world_creator/json_converter.py
> +            walls.append([p1, p2])
Пока на локальной ветке refacroting реализована часть, связанная с InterfaceObject. Подумаю над тем, чтобы сделать тоже самое с GazeboObject.

2019-11-08 16:34 UTC, KaiL4eK requested changes
Закрываем это и готов смержить

2019-11-08 16:34 UTC, KaiL4eK commented on world_creator/data_structures.py
> +        return Point2D(self.x / other, self.y / other)
Ну так не делается, у тебя в базовом классе конструкция дочернего класса)

2019-11-08 16:34 UTC, KaiL4eK commented on world_creator/README.md
> +After that you should consistently click on buttons `create json` and `create sdf from json`.
Вот в том и дело, что для генерации нужны зависимости (PyQt и мб другие), которые реально не требуются для генерации SDF

2019-11-08 16:34 UTC, KaiL4eK commented on world_creator/data_structures.py
> +        return Point2D(self.x / other, self.y / other)
Это приводит к тому, что деление двух Vector2D порождает Point2D. Эдакий бастард в мире ООП)

2019-11-08 16:34 UTC, KaiL4eK commented on world_creator/json_constants.py
> +    STOP = PATH_TO_IMAGE + 'stop_sign.png'
соединения путей лучше делать через os.path.join()

2019-11-08 16:34 UTC, KaiL4eK commented on world_creator/json_converter.py
> +SDF_DEFAULT_NAME = "../wr8_description/worlds/world.world"
Эм, так это не изменилось?)

2019-11-08 16:34 UTC, KaiL4eK commented on world_creator/requirements.txt
> +lxml>=4.4.1
PyQt не попадает сюда?

2019-11-10 18:09 UTC, PonomarevDA commented on world_creator/data_structures.py
> +        return Point2D(self.x / other, self.y / other)
Исправлено

2019-11-10 18:09 UTC, PonomarevDA commented on world_creator/json_constants.py
> +    STOP = PATH_TO_IMAGE + 'stop_sign.png'
Исправлено

2019-11-10 18:09 UTC, PonomarevDA commented on world_creator/requirements.txt
> +lxml>=4.4.1
Добавил pyqt5

2019-11-10 20:12 UTC, KaiL4eK approved these changes

2019-11-11 09:11 UTC, merged