Feature/parking
serykhelena/AutoNetChallenge pull request #36
Opened 2020-02-09 20:19 UTC by PonomarevDA

2020-02-15 19:32 UTC, KaiL4eK commented
Пока что мельком просмотрел - сразу небольшой совет, в данном случае можно было создать отдельный .rviz файл для просмотра состояния системы паркинга, так как она имеет специфичные топики и расположение.

2020-02-15 20:07 UTC, PonomarevDA commented
> Пока что мельком просмотрел - сразу небольшой совет, в данном случае можно было создать отдельный .rviz файл для просмотра состояния системы паркинга, так как она имеет специфичные топики и расположение.

waypoint_planner тоже содержит специфичный топик - путь по точкам.
Если для каждого случая делать свой rviz файл - их количество будет расти в геометрической прогрессии. 
В rviz есть удобная возможность создавать группы - они и используются.

2020-02-16 08:44 UTC, KaiL4eK commented
Все верно, ради каждого топика не требуется создавать новый rviz, суть скорее в разбиении по задачам, задачи slam, localization, parking, lidar. Это полезно, когда требуется отладить и посмотреть конкретные вещи по отлаживаемой задаче.

2020-02-16 15:11 UTC, KaiL4eK requested changes
- Изменить публикуемую логику на значение заполнения
- Сгруппировать топики в rviz

2020-02-16 15:11 UTC, KaiL4eK commented on wr8_software/config/global_costmap_params.yaml
> -  #  static_map: false
Удалить вот это =)

2020-02-16 15:11 UTC, KaiL4eK commented on car_parking/msg/Statuses.msg
> +uint8[] statuses
Изменить логику на fillness + status (string)

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/scripts/car_parking_test.py
> +
рекомендую для выделения main кода пользовать конструкцию
if __name__ == "__main__":

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/src/parking_node.cpp
> +static const char* POLY_SUB_TOPIC = "/parking_polygones";
не стоит пользоваться /, так как это может отразиться на формировании имени при использовании namespace

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/src/parking_node.cpp
> +static const char* GRID_SUB_TOPIC = "/move_base/global_costmap/costmap";
лучше задать дефолтное имя, а через remap в launch сделать маппинг

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/src/parking_node.cpp
> +            ROS_INFO("Waiting for START cmd...");
Ух, лучше вывод такого делать через ROS_DEBUG_THROTTLE
http://wiki.ros.org/roscpp/Overview/Logging

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/src/parking_node.cpp
> +            ROS_INFO("Waiting for START cmd...");
а то при увеличении частоты будет жутко спамить)

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/src/parking_node.cpp
> +            ROS_INFO("UpdateGrid() is calling.");
Это все же больше отладочная инфа - ROS_DEBUG()

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/src/parking_core.cpp
> +        ROS_WARN("Core: Grid is nullptre or poly is empty!");
nullptre =)

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/src/parking_core.cpp
> +    for(auto i = polygons_.begin(); i != polygons_.end(); i++){
Даже при итерации лучше использовать более говорящее имя, i - исходно использовался под индекс, в данном случае это больше, чем число

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/src/parking_core.cpp
> +        CalculateEdgeIndexes(*polygon, polygons_.back().min_x, polygons_.back().max_x,
Честно говоря, не очень понял данной необходимости разместить объект в векторе, и только потом его заполнять. Думаю, лучше создать объект, обработать и потом разместить в векторе, так не придется в back() тянуться.

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/src/parking_core.cpp
> +bool CarParking::IsPolygonConvex(const car_parking::Points2D& poly){
Шикарная функция =)

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/src/parking_core.cpp
> +    if(max_value <= 80){
Я бы тут проверил на работоспособность алгоритма при малом пересечении объектом зоны. Также, мы все еще можем парковаться, когда зона занята очень с краю, но центр свободен - конечно, такой кейс можно обработать, просто задав исходные зоны поменьше, но все же)

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/src/parking_core.cpp
> +    if(max_value <= 80){
Просто за счет заполненности не очень понятно, где она заполнена. Может по краям куча мусора, а центр свободен, или тонкий столб по-центру стоит, который по площади не более 5%, но лидар все таки видит.

2020-02-16 16:27 UTC, KaiL4eK commented on car_parking/src/parking_core.cpp
> +    if(max_value <= 80){
Поэтому то и не уверен, насчет того, стоит ли переходить на формат "количество заполнения".

2020-02-16 19:11 UTC, PonomarevDA commented on car_parking/src/parking_core.cpp
> +        CalculateEdgeIndexes(*polygon, polygons_.back().min_x, polygons_.back().max_x,
Между размещением объекта в векторе и последующим его заполнением, есть проверка, корректен ли полигон (IsPolygonConvex() - в теории должна проверять, является ли полигон выпуклым, на деле там пустышка, т.к. пока мы доверяем юзеру).
Количество полигонов (элементов вектора) должно соответствовать количеству статусов.
Поэтому и объект сначала размещается, а потом заполняется.

Другое дело - можно вместо передачи 4 аргументов с back() передать одну ссылку на структуру PolygonInfo.

2020-02-28 21:13 UTC, KaiL4eK approved these changes

2020-02-28 21:13 UTC, merged