add simple catkin build workflow
serykhelena/AutoNetChallenge pull request #57
Opened 2022-01-26 17:35 UTC by PonomarevDA

I've added a simple catkin build workflow using GitHub actions based on `DEVELOPMENT.md`.
Here I've also fixed `DEVELOPMENT.md` because it had a wrong installation script name and added an ability to throw "-y" for install_pkgs.sh script to make it usable during the workflow.
Although this workflow is based on Ubuntu-18.04, it might be changed to 20.04 in future if it will be required for somebody.

2022-02-12 20:44 UTC, KaiL4eK commented
Looks great! I think we should use such check in all ROS-connected project! Thanks. Are you gonna add something or we can merge?

2022-02-12 20:44 UTC, KaiL4eK requested changes

2022-02-12 20:44 UTC, KaiL4eK commented on .github/workflows/catkin_build.yml
> +    runs-on: ubuntu-18.04
Now repo works on noetic - I think we should be based on it and moreover use python-3.8

2022-02-12 20:46 UTC, KaiL4eK commented on scripts/install_pkgs.sh
> +					$1 && \
To passthrough all options you can use `$@`

2022-02-18 16:49 UTC, PonomarevDA commented on .github/workflows/catkin_build.yml
> +    runs-on: ubuntu-18.04
fixed

2022-02-18 16:50 UTC, PonomarevDA commented on scripts/install_pkgs.sh
> +					$1 && \
fixed

2022-02-18 19:34 UTC, KaiL4eK approved these changes
Great!

2022-02-18 19:35 UTC, merged